name: release

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          # if we are not at v1.0.0 yet, breaking changes do not need to add a new major version
          bump-minor-pre-major: true
          pull-request-title-pattern: "chore: ${scope} release${component} ${version}"

