name: test

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read


jobs:
  test:
    name: run make test
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.gh_pat }}
          submodules: pwdrecursive
      - name: Set up Dev Containers CLI
        uses: devcontainers/cli-action@v0.5.2
      - name: Build and run devcontainer
        run: |
          devcontainer up --workspace-folder . --skip-post-attach
      - name: Run Tests in Devcontainer
        # Assumes that all repositories have a make test target
        run: |
          devcontainer exec --workspace-folder . "make test" 



