name: test

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read


jobs:
  test:
    name: run make test
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: aselabsvu/dev
      volumes:
        - ${{ github.workspace }}:/app
      env:
        PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/go/bin:/root/go/bin
        GOFLAGS: -buildvcs=false

    steps:
      - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.gh_pat }}
          submodules: pwdrecursive
      # - run: make test
      - run: id
      - run: echo $USER
      - run: echo $HOME


