name: test

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read


jobs:
  lint:
    name: run make lint
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: aselabsvu/dev-root
      # options: --privileged

    steps:
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.21"
      #     cache: false
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.gh_pat }}
          submodules: recursive
      - run: make lint
      # - run: sudo apt update && sudo apt install pkg-config libzmq3-dev protobuf-compiler
      # - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.55
      #     skip-pkg-cache: true



  tests:
    name: run make test
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: aselabsvu/dev-root
      options: --privileged

    steps:
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: "1.21"
      #     cache: false
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.gh_pat }}
          submodules: recursive
      # - run: sudo apt update && sudo apt install pkg-config libzmq3-dev protobuf-compiler
      # - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      # - name: Run tests
      - run: make test